### ISSUE TITLE
sort not working

### ISSUE THREAD

**Issue by balajis5531** [fssa-batch3/hemanath.muralikrishnan__web_project#11]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTI2MTViOGEtOTkwMi00OWMxLWI4MGEtYjcxZjc2ZWY3NWQ3IiwiZGVwbG95X2lkIjoiNjQ2MzE5YTljMThmYjAwMDA4ZGU0YTJkIiwiaWQiOiIzNGVlMWE5ZS05YWNjLTRiZDEtYWI2OC0wNzZjZjBiNGQ0NDkifQ==)

### Description of issue
i want3 types of fruits, so i click sort function this show only one type but i click 3.

### Expected result
this show what i type i want that type all show in the page

### Actual result
i click three categories but show one category.

### Steps to reproduce
1. go to the product page
2. click categories
3. 

```
Path:      /pages/product_list/list_product.html?cat=00
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--agrokart.netlify.app%2Fpages%2Fproduct_list%2Flist_product.html%3Fcat%3D00&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--agrokart.netlify.app/pages/product_list/list_product.html?cat=00)

**Comment by Hemanath78** [comment]
Issue was solved.
