### ISSUE TITLE
Pop-up

### ISSUE THREAD

**Issue by nithilans** [fssa-batch3/hemanath.muralikrishnan__web_project#4]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTI2MTViOGEtOTkwMi00OWMxLWI4MGEtYjcxZjc2ZWY3NWQ3IiwiZGVwbG95X2lkIjoiNjQ0NjI2MGY1OTI4MGYwMDA4YTQzZGEzIiwiaWQiOiJhMTNlYmNhMS0zMDlmLTQ3ZmYtODJmZi05N2U2ZWI3MzExYjQifQ==)

### Description of issue
If new user login, it is not showing that he is new to the website and not asking to create an account.

### Expected result
It should return pop-up with title you are new to the website create an account.

### Actual result
But It is not showing the pop-up.

### Steps to reproduce
1. first I went to login page in his website and logged in with details.
2. I have entered nithilan@gmail.com in email input field, but it is not showing any pop-up to create a new account.
3. 

```
Path:      /index.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--agrokart.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--agrokart.netlify.app/index.html)

**Comment by Hemanath78** [comment]
The above bug was fixed.👍

**Comment by nithilans** [comment]
ok
