### ISSUE TITLE
add to card count not increase 

### ISSUE THREAD

**Issue by balajis5531** [fssa-batch3/hemanath.muralikrishnan__web_project#5]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTI2MTViOGEtOTkwMi00OWMxLWI4MGEtYjcxZjc2ZWY3NWQ3IiwiZGVwbG95X2lkIjoiNjQ1MjFkNmMzNThkMjgwMDA4NzBmYzA1IiwiaWQiOiJmMmI0YWJlMS1lMjkxLTQ0YjUtOWRiYi01NTIyYWU2YmQ0MjUifQ==)

### Description of issue
 -in the add to card icon I click add to cart not count increase

### Expected result
 -I click add to cart increase the count in add to cart icon

### Actual result
- this actual result not count increase in icon top.

### Steps to reproduce
1. I click add to cart
2. go to up see the add to cart icon not increase count 
3. it show only 0

```
Path:      /index.html
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--agrokart.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--agrokart.netlify.app/index.html)

**Comment by Hemanath78** [comment]
The above bug was fixed.👍
