### ISSUE TITLE
not check validation in profile update page.

### ISSUE THREAD

**Issue by balajis5531** [fssa-batch3/hemanath.muralikrishnan__web_project#6]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTI2MTViOGEtOTkwMi00OWMxLWI4MGEtYjcxZjc2ZWY3NWQ3IiwiZGVwbG95X2lkIjoiNjQ1MjFkNmMzNThkMjgwMDA4NzBmYzA1IiwiaWQiOiJiZjc5MGUzMy1lYjMzLTQ0OGQtYjY2Zi1iYzQwMWMyZmJhMjYifQ==)

### Description of issue
in profile page not check first name and last name not check correct validation.

### Expected result
the edit the profile check validation and submit

### Actual result

this profile page edit  not check validation in first name last name submit number.

### Steps to reproduce
1. go to profile page
2. click the edit button,
3. first name and last name input type number 

```
Path:      /pages/profile.html
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--agrokart.netlify.app%2Fpages%2Fprofile.html&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--agrokart.netlify.app/pages/profile.html)

**Comment by Hemanath78** [comment]
The above bug was fixed.👍
