### ISSUE TITLE
the search bar not show not result found

### ISSUE THREAD

**Issue by balajis5531** [fssa-batch3/hemanath.muralikrishnan__web_project#7]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTI2MTViOGEtOTkwMi00OWMxLWI4MGEtYjcxZjc2ZWY3NWQ3IiwiZGVwbG95X2lkIjoiNjQ1MjFkNmMzNThkMjgwMDA4NzBmYzA1IiwiaWQiOiI1NzZmYWEwNS0yMzE0LTQwM2QtYjMwNS05YzA2N2YwOWNlOTUifQ==)

### Description of issue
search bar not showing no result found

### Expected result
I am search any unwanted items this show no result found

### Actual result
search bar not showing  no result found 

### Steps to reproduce
1. click the search bar .
2. type unwanted things
3. this show blank.

```
Path:      /
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--agrokart.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--agrokart.netlify.app/)

**Comment by Hemanath78** [comment]
The above bug was fixed.👍
