### ISSUE TITLE
available quantity not cheeking

### ISSUE THREAD

**Issue by balajis5531** [fssa-batch3/hemanath.muralikrishnan__web_project#8]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTI2MTViOGEtOTkwMi00OWMxLWI4MGEtYjcxZjc2ZWY3NWQ3IiwiZGVwbG95X2lkIjoiNjQ2MzE5YTljMThmYjAwMDA4ZGU0YTJkIiwiaWQiOiI3ZjRjYTZlZS1iOTUyLTQ4MjEtYjUzMy02YWIyZWYzZTQzOTIifQ==)

### Description of issue
the details page available quantity not checking

### Expected result
this expect result is what is available quality check and user click more than available quantity show alert. 

### Actual result
not check available quality 

### Steps to reproduce
1.  click any product go to the product details page 
2. click quantity its not checking
3. 

```
Path:      /pages/product_details/details.html?id=17&cat=02
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--agrokart.netlify.app%2Fpages%2Fproduct_details%2Fdetails.html%3Fid%3D17%26cat%3D02&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--agrokart.netlify.app/pages/product_details/details.html?id=17&cat=02)

**Comment by Hemanath78** [comment]
Issue was resolved.
