### ISSUE TITLE
navigation

### ISSUE THREAD

**Issue by balajis5531** [fssa-batch3/hemanath.muralikrishnan__web_project#9]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTI2MTViOGEtOTkwMi00OWMxLWI4MGEtYjcxZjc2ZWY3NWQ3IiwiZGVwbG95X2lkIjoiNjQ2MzE5YTljMThmYjAwMDA4ZGU0YTJkIiwiaWQiOiJiMDhjMzEzYy1kYjQzLTRjNWItOGZmZi1kN2JjN2E4ZTU3YjcifQ==)

### Description of issue
the navigation not working , the text show static.

### Expected result
the shop text click this go to shop page.

### Actual result
this is not working .

### Steps to reproduce
1.  go to the details page
2. click button  shop navigation  
3. 

```
Path:      /pages/product_details/details.html?id=17&cat=02
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--agrokart.netlify.app%2Fpages%2Fproduct_details%2Fdetails.html%3Fid%3D17%26cat%3D02&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--agrokart.netlify.app/pages/product_details/details.html?id=17&cat=02)

**Comment by Hemanath78** [comment]
Issue was solved.
